// flow-typed signature: d7b94f77d4b3f4024077358528730e7b
// flow-typed version: <<STUB>>/file-saver_v2.0.5/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-saver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-saver' {
  declare module.exports: any;
}
