// flow-typed signature: 517709c00e80fb02b2becfa5ca7f1cd2
// flow-typed version: <<STUB>>/iso-639-1_v2.1.4/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iso-639-1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iso-639-1' {
  declare module.exports: any;
}
