// @flow
export const LANGUAGES :string[] = [
  'Abkhazian',
  'Afar',
  'Afrikaans',
  'Akan',
  'Albanian',
  'Alemannic',
  'Amharic',
  'Angal',
  'Anglo-Saxon / Old English',
  'Arabic',
  'Aragonese',
  'Aramaic',
  'Armenian',
  'Aromanian',
  'Arpitan / Franco-Provençal',
  'Assamese',
  'Asturian',
  'Avar',
  'Awadhi',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Banyumasan',
  'Bashkir',
  'Basque',
  'Bavarian',
  'Belarusian (Taraškievica)',
  'Belarusian',
  'Bengali',
  'Bihari',
  'Bikol',
  'Bishnupriya Manipuri',
  'Bislama',
  'Bosnian',
  'Breton',
  'Buginese',
  'Bulgarian',
  'Buriat (Russia)',
  'Burmese',
  'Cambodian',
  'Cantonese',
  'Catalan',
  'Cebuano',
  'Chamorro',
  'Chechen',
  'Cherokee',
  'Cheyenne',
  'Chichewa',
  'Chinese',
  'Choctaw',
  'Chuvash',
  'Classical Chinese',
  'Cornish',
  'Corsican',
  'Cree',
  'Creek / Muskogee',
  'Croatian',
  'Czech',
  'Danish',
  'Dimli',
  'Divehi',
  'Dutch Low Saxon',
  'Dutch',
  'Dzongkha',
  'English',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Extremaduran',
  'Faroese',
  'Fijian',
  'Finnish',
  'French',
  'Friulian',
  'Galician',
  'Gan Chinese',
  'Ganda',
  'Garhwali',
  'Georgian',
  'German',
  'Gilbertese',
  'Gothic',
  'Greek',
  'Greenlandic',
  'Guarani',
  'Gujarati',
  'Haitian',
  'Hakka Chinese',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Herero',
  'Hindi',
  'Hiri Motu',
  'Hungarian',
  'Icelandic',
  'Ido',
  'Igbo',
  'Ilokano',
  'Indonesian',
  'Ingush',
  'Interlingua',
  'Interlingue',
  'Inuktitut',
  'Inupiak',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kalmyk',
  'Kannada',
  'Kanuri',
  'Kapampangan',
  'Kashmiri',
  'Kashubian',
  'Kazakh',
  'Khowar',
  'Kikuyu',
  'Kirghiz',
  'Kirundi',
  'Klingon',
  'Komi',
  'Kongo',
  'Korean',
  'Kuanyama',
  'Kurdish',
  'Ladino / Judeo-Spanish',
  'Lango',
  'Laotian',
  'Latin',
  'Latvian',
  'Laz',
  'Ligurian',
  'Limburgian',
  'Lingala',
  'Lithuanian',
  'Lojban',
  'Lombard',
  'Low German / Low Saxon',
  'Lower Sorbian',
  'Luxembourgish',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Mandarin',
  'Manx',
  'Maori',
  'Mara',
  'Marathi',
  'Marshallese',
  'Megrelian',
  'Min Dong Chinese',
  'Minangkabau',
  'Minnan',
  'Mirandese',
  'Moldovan',
  'Mongolian',
  'Nahuatl',
  'Nauruan',
  'Navajo',
  'Ndonga',
  'Neapolitan',
  'Nepali',
  'Newar',
  'Norfolk',
  'Norman',
  'North Ndebele',
  'Northern Sami',
  'Northern Sotho',
  'Norwegian Nynorsk',
  'Norwegian',
  'Occitan',
  'Ojibwa',
  'Old Church Slavonic / Old Bulgarian',
  'Oriya',
  'Oromo',
  'Ossetian / Ossetic',
  'Pali',
  'Pangasinan',
  'Panjabi / Punjabi',
  'Papiamentu',
  'Pashto',
  'Pennsylvania German',
  'Persian',
  'Peul',
  'Piedmontese',
  'Polish',
  'Portuguese',
  'Quechua',
  'Raeto Romance',
  'Ripuarian',
  'Romani',
  'Romanian',
  'Russian',
  'Rwandi',
  'Samoan',
  'Samogitian',
  'Sango',
  'Sanskrit',
  'Sardinian',
  'Scots',
  'Scottish Gaelic',
  'Serbian',
  'Serbo-Croatian',
  'Shona',
  'Sichuan Yi',
  'Sicilian',
  'Simple English',
  'Sindhi',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somalia',
  'South Ndebele',
  'Southern Sotho',
  'Spanish',
  'Sundanese',
  'Swahili',
  'Swati',
  'Swedish',
  'Tagalog',
  'Tahitian',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Tetum',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tok Pisin',
  'Tonga',
  'Tsonga',
  'Tswana',
  'Tumbuka',
  'Turkish',
  'Turkmen',
  'Twi',
  'Udmurt',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Venda',
  'Venetian',
  'Vietnamese',
  'Volapük',
  'Võro',
  'Walloon',
  'Waray / Samar-Leyte Visayan',
  'Welsh',
  'West Flemish',
  'West Frisian',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang',
  'Zulu',
];
