/*
 * @flow
 */

import { FormConstants } from '../../containers/profile/src/constants';

const {
  REFERRAL_FORM,
  INTAKE_FORM,
  RESTITUTION_REFERRAL_FORM,
  PEACEMAKER_INFORMATION_FORM,
} = FormConstants;

const ROOT :'/' = '/';

const PERSON_ID :string = ':personId';

const PEACEMAKER_INFORMATION :string = 'peacemakerinformation';
const PEACEMAKER_INFORMATION_ROUTE_END :string = `${PERSON_ID}/${PEACEMAKER_INFORMATION}`;

const REFERRAL :string = 'referral';
const REFERRAL_ROUTE_END :string = `${PERSON_ID}/${REFERRAL}`;

const FORM_ID :string = ':formId';
const COMPLETED_REFERRAL :string = 'completedreferral';
const COMPLETED_REFERRAL_ROUTE_END :string = `${PERSON_ID}/${COMPLETED_REFERRAL}/${FORM_ID}`;

const REPAIR_HARM_AGREEMENT :string = 'repairharmagreement';
const REPAIR_HARM_AGREEMENT_ROUTE_END :string = `${PERSON_ID}/${REPAIR_HARM_AGREEMENT}`;

const COMPLETED_REPAIR_HARM_AGREEMENT :string = 'completedrepairharmagreement';
const COMPLETED_REPAIR_HARM_AGREEMENT_ROUTE_END :string = `${PERSON_ID}/${COMPLETED_REPAIR_HARM_AGREEMENT}`;

const ROUTES_FOR_COMPLETED_FORMS = {
  [FormConstants.REPAIR_HARM_AGREEMENT]: COMPLETED_REPAIR_HARM_AGREEMENT_ROUTE_END,
  [INTAKE_FORM]: ROOT,
  [PEACEMAKER_INFORMATION_FORM]: PEACEMAKER_INFORMATION_ROUTE_END,
  [REFERRAL_FORM]: COMPLETED_REFERRAL_ROUTE_END,
  [RESTITUTION_REFERRAL_FORM]: ROOT,
};

export {
  COMPLETED_REFERRAL,
  COMPLETED_REFERRAL_ROUTE_END,
  COMPLETED_REPAIR_HARM_AGREEMENT,
  COMPLETED_REPAIR_HARM_AGREEMENT_ROUTE_END,
  FORM_ID,
  PEACEMAKER_INFORMATION,
  PEACEMAKER_INFORMATION_ROUTE_END,
  PERSON_ID,
  REFERRAL,
  REFERRAL_ROUTE_END,
  REPAIR_HARM_AGREEMENT,
  REPAIR_HARM_AGREEMENT_ROUTE_END,
  ROOT,
  ROUTES_FOR_COMPLETED_FORMS,
};
